
title: DeepSpeed
email: deepspeed@microsoft.com
description: >-
  DeepSpeed is a deep learning optimization library that makes distributed
  training easy, efficient, and effective.

locale : "en-US"

repository: microsoft/DeepSpeed
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.9.0"
minimal_mistakes_skin : "air"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate

paginate: 10
paginate_path: /blog/page:num

include: ["_pages"]

collections:
  tutorials:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: true
      related: false
  # _tutorials
  - scope:
      path: ""
      type: tutorials
    values:
      layout: single

# Outputting
permalink: /:categories/:title/
timezone: America/Los_Angeles

breadcrumbs: true

category_archive:
  type: liquid
  path: /categories/
